repos:
  - repo: local
    hooks:
      - id: glab-docs
        name: glab-docs
        entry: go run ./cmd/glab-docs
        language: system
        pass_filenames: false
        files: (README\.md\.gotmpl|\.gitlab-ci\.ya?ml|/templates/.*\.ya?ml)$
        args:
          - --search-root=.
          - --component-prefix=gitlab.com/m13tlabs/glab-docs
