- id: glab-docs
  args: []
  description: Uses 'glab-docs' to generate documentation from a GitLab CI component's spec:inputs and variables, and writes it to a corresponding 'README.md' file.
  entry: git-hook/glab-docs
  files: (README\.md\.gotmpl|\.gitlab-ci\.ya?ml|/templates/.*\.ya?ml)$
  language: script
  name: glab-docs
  require_serial: true

- id: glab-docs-built
  args: []
  description: Uses auto built 'glab-docs' to generate documentation from a GitLab CI component's spec:inputs and variables, and writes it to a corresponding 'README.md' file.
  entry: glab-docs
  files: (README\.md\.gotmpl|\.gitlab-ci\.ya?ml|/templates/.*\.ya?ml)$
  language: golang
  name: glab-docs built
  require_serial: true

- id: glab-docs-container
  args: []
  description: Uses the container image of 'glab-docs' to generate documentation from a GitLab CI component's spec:inputs and variables, and writes it to a corresponding 'README.md' file.
  entry: m13tlabs/glab-docs:latest
  files: (README\.md\.gotmpl|\.gitlab-ci\.ya?ml|/templates/.*\.ya?ml)$
  language: docker_image
  name: glab-docs container
  require_serial: true
